### ISSUE TITLE
CustomResourceHandler can't works with sub-resource 

### ISSUE THREAD

**Issue by songdongsheng** [Erudika/para#12]
When I create CustomResourceHandler with relativePath = '/myprefix/usermgr/', then my handler got request from:
    /v1/myprefix/usermgr
    /v1/myprefix/usermgr/
    /v1/myprefix/usermgr?queryString

But not sub-resource, e.g.
    /v1/myprefix/usermgr/{type}
    /v1/myprefix/usermgr/{type}/
    /v1/myprefix/usermgr/{type}/{id}
    /v1/myprefix/usermgr/{type}/{id}/

Para return 404, how can CustomResourceHandler works with sub-resource ?

**Comment by albogdano** [comment]
Have you tried creating separate `CustomResourceHandler` for `/v1/myprefix/usermgr`, `/v1/myprefix/usermgr/{type}` and `/v1/myprefix/usermgr/{type}/{id}`? The `relativePath` can contain Jersey style placeholders like `{id}`, but you might need to create a handler for each path.

**Comment by songdongsheng** [comment]
Do you mean I must create 3 CustomResourceHandler ? i.e. one for /v1/myprefix/usermgr/, one for /v1/myprefix/usermgr/{type}, one for /v1/myprefix/usermgr/{type}/{id} ?

**Comment by albogdano** [comment]
Yes, try that.

**Comment by songdongsheng** [comment]
Great, it works !
