### ISSUE TITLE
terms search not works

### ISSUE THREAD

**Issue by songdongsheng** [Erudika/para#13]
Basic search give me 2 records:

$ curl -i -X GET \
    -H "Authorization: Bearer${access_token}" \
    http://127.0.0.1:8080/v1/search?q=type:mytest

HTTP/1.1 200 OK
Date: Tue, 13 Jun 2017 10:24:36 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json
Content-Length: 847

{
  "totalHits" : 2,
  "page" : 0,
  "items" : [ {
    "id" : "785445575716769792",
    "timestamp" : 1497349402816,
    "type" : "mytest",
    "appid" : "mybaas",
    "creatorid" : "782839067418038272",
    "name" : "Salesforce 广州",
    "votes" : 0,
    "stored" : true,
    "indexed" : false,
    "cached" : true,
    "objectURI" : "/mytests/785445575716769792",
    "plural" : "mytests",
    "billingStreet" : "广州"
  }, {
    "id" : "785445575716769793",
    "timestamp" : 1497349402816,
    "type" : "mytest",
    "appid" : "mybaas",
    "creatorid" : "782839067418038272",
    "name" : "Salesforce 佛山",
    "votes" : 0,
    "stored" : true,
    "indexed" : false,
    "cached" : true,
    "objectURI" : "/mytests/785445575716769793",
    "plural" : "mytests",
    "billingStreet" : "佛山"
  } ]
}

But I search by name field which include 'Salesforce', no results:

$ curl -i -X GET \
    -H "Authorization: Bearer${access_token}" \
    "http://127.0.0.1:8080/v1/search/terms?terms=name:Salesforce"
HTTP/1.1 200 OK
Date: Tue, 13 Jun 2017 10:24:46 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json
Content-Length: 56

{
  "totalHits" : 0,
  "page" : 0,
  "items" : [ ]
}

**Comment by albogdano** [comment]
Yes, apparently it's case sensitive... try "http://127.0.0.1:8080/v1/search/terms?terms=name:salesforce"
I haven't noticed this before, it appears that Elasticsearch stores terms in lowercase.

**Comment by songdongsheng** [comment]
yes, lowercase works, but the search should not care about terms case.

Search Chinese terms can not found any thing too:

"http://127.0.0.1:8080/v1/search/terms?terms=name:佛山"
"http://127.0.0.1:8080/v1/search/terms?terms=name:%E4%BD%9B%E5%B1%B1"

**Comment by albogdano** [comment]
You are right @songdongsheng, queries should be case-insensitive but this is just how ES works for term queries. Try using the querystring query with `q=name:Salesforce` as an alternative. 

All I could do here is set the `name` field to `not_analyzed`. But for any other of your custom fields this will still be an issue unless you create a mapping with `not_analyzed` for each field. For more information see https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html#_analyzer

If you look inside `ElasticSearchUtils` there's a list of default mappings for the core fields in `ParaObject`.
