### ISSUE TITLE
Can you run multiple para nodes using the Lucene index backend?

### ISSUE THREAD

**Issue by kobus-v-schoor** [Erudika/para#140]
Hi there, just want to check if using multiple para nodes behind a load balancer can use the lucene backend for indexing? Will the indices be kept in sync somehow? Or should we rather switch over to Elastic when using multiple nodes?

Thanks!

**Comment by albogdano** [comment]
Lucene is suitable for single-node setups because it stores data locally and doesn't support clustering. Elasticsearch is more suitable for multi-node deployments behind a load balancer.

**Comment by kobus-v-schoor** [comment]
Thanks @albogdano, appreciate the feedback
