### ISSUE TITLE
Username's domain is stripped out even when AD domain is empty

### ISSUE THREAD

**Issue by kobus-v-schoor** [Erudika/para#141]
When `ad_mode_enabled` is set to `true`, but `active_directory_domain` is set to an empty string, Para still strips off the domain given in the username even though it shouldn't. Spring's AD auth provider supports setting empty AD domains, but the username should then always include the domain. This mode is useful when an AD directory contains more than one domain (e.g. `@company.com` and `@holding-corp.com`)

As it currently stands, if AD mode is explicitly enabled with an empty AD domain the domain still gets stripped, meaning that authentication fails. Para should detect this and pass the whole username through in this case to the AD backend

**Comment by albogdano** [comment]
Thanks a lot! I had a feeling something was broken in the LDAP authentication class with regards to AD. Probably related to Erudika/scoold#67
