### ISSUE TITLE
Password authentication - what is the correct way to create users?

### ISSUE THREAD

**Issue by mattcopas** [Erudika/para#16]
Hi guys,

I'm having difficulty logging in using password authentication with users I've created:

I created the user using a POST request to http://localhost:8080/v1/user with the data: 
{

    "email":"test@test.test",
    "identifier":"test@test.test",
    "password":"$2y$10$uaxFpt2jXScScYV0AEm1TeruIUuPjOAC.3F9GftRA5a0I3i/F5ai6",
    "username":"testuser2"

}

I've also tried using a non-hashed password:

{

    "email":"test@test.test",
    "identifier":"test@test.test",
    "password":"password",
    "username":"testuser2"

}

Both the users were created fine,

However I can't authenticate using the form provided in the docs:

 <form method="post" action="http://localhost:8080/password_auth">
     <input type="email" name="email">
     <input type="password" name="password">
     <input type="submit">
 </form>

I've got to the point of running Para via the source code so that I can debug the PasswordAuthenticationFilter, and have found that the storedHash is coming back blank, hence the password's don't match.

I've also searched for the users in the REST API and Elasticsearch itself, but there's no stored hash anywhere....

{
  "totalHits" : 2,
  "page" : 0,
  "items" : [ {
    "id" : "795270796749574144",
    "timestamp" : 1499691918054,
    "type" : "user",
    "appid" : "para",
    "name" : "ParaObject 1499691917825",
    "votes" : 0,
    "stored" : true,
    "indexed" : false,
    "cached" : true,
    "identifier" : "test@test.test",
    "groups" : "users",
    "active" : false,
    "twoFA" : false,
    "email" : "test@test.test",
    "currency" : "EUR",
    "picture" : "https://www.gravatar.com/avatar?d=mm&size=400",
    "identityProvider" : "generic",
    "plural" : "users",
    "objectURI" : "/users/795270796749574144"
  }, {
    "id" : "795229488181940224",
    "timestamp" : 1499682069324,
    "type" : "user",
    "appid" : "para",
    "name" : "ParaObject 1499682069110",
    "votes" : 0,
    "stored" : true,
    "indexed" : false,
    "cached" : true,
    "identifier" : "test@test.com",
    "groups" : "users",
    "active" : false,
    "twoFA" : false,
    "email" : "test@test.com",
    "currency" : "EUR",
    "picture" : "https://www.gravatar.com/avatar?d=mm&size=400",
    "identityProvider" : "generic",
    "plural" : "users",
    "objectURI" : "/users/795229488181940224"
  } ]
}

Any advice would be really good :)

Many thanks

**Comment by albogdano** [comment]
Your user is not active. Set `active = true` or enable unverified emails with `para.security.allow_unverified_emails = true` in `application.conf`.

**Comment by mattcopas** [comment]
I tried making both users active with a patch request - still the stored hash password is coming back blank (which I can see from my debug logging)

{
  "totalHits" : 2,
  "page" : 0,
  "items" : [ {
    "id" : "795270796749574144",
    "timestamp" : 1499691918054,
    "type" : "user",
    "appid" : "para",
    "updated" : 1499698798105,
    "name" : "ParaObject 1499691917825",
    "votes" : 0,
    "stored" : true,
    "indexed" : false,
    "cached" : true,
    "identifier" : "test@test.test",
    "groups" : "users",
    "active" : true,
    "twoFA" : false,
    "email" : "test@test.test",
    "currency" : "EUR",
    "picture" : "https://www.gravatar.com/avatar?d=mm&size=400",
    "identityProvider" : "generic",
    "plural" : "users",
    "objectURI" : "/users/795270796749574144"
  }, {
    "id" : "795229488181940224",
    "timestamp" : 1499682069324,
    "type" : "user",
    "appid" : "para",
    "updated" : 1499698811633,
    "name" : "ParaObject 1499682069110",
    "votes" : 0,
    "stored" : true,
    "indexed" : false,
    "cached" : true,
    "identifier" : "test@test.com",
    "groups" : "users",
    "active" : true,
    "twoFA" : false,
    "email" : "test@test.com",
    "currency" : "EUR",
    "picture" : "https://www.gravatar.com/avatar?d=mm&size=400",
    "identityProvider" : "generic",
    "plural" : "users",
    "objectURI" : "/users/795229488181940224"
  } ]
}

**Comment by albogdano** [comment]
First of all, you shouldn't create users manually with `POST /v1/user`, second, the password is provided in plaintext and Para hashes it for you. For security reasons the hash is hidden from the user object that is returned from the API (but it's there in the DB).

**Comment by mattcopas** [comment]
I know manual user creation isn't the norm - I'm only using it until I can get the sign in functionality working - thanks for the note that a plain password should be provided.

I've tried creating a user via the para client as part of my app initialisation as so:

       @Bean
	public User createDefaultUserBean(ScooldUtils utils) {
		ParaClient pc = utils.getParaClient();
		String email = "default@default.test";
		User defaultUser = new User("defaultuser");
		defaultUser.setIdentifier(email);
		defaultUser.setPassword("password");
		defaultUser.setEmail(email);
		defaultUser.setActive(true);
		return pc.create(defaultUser);
	}

However, now when I try and sign in with this user, I get a null pointer for the user that is passed to passwordsMatch(User u) - I've verified that this defaultuser is persisted, both via the Para REST API and elasticsearch...

Thanks for your help.

**Comment by albogdano** [comment]
How exactly do you sign in with that email and password?

**Comment by mattcopas** [comment]
With the form mentioned above - ie a POST request to http://localhost:8080/password_auth containing the email and password of the user

**Comment by albogdano** [comment]
You are setting the user `id` manually to "defaultuser" which causes the client to make a PUT request. Try removing that id and just write `User defaultUser = new User();`

**Comment by mattcopas** [comment]
That fixed the NullPointer - however I have the same issue as with the manually created users. Is there a way to expose the password/hashed password for debugging purposes?

**Comment by albogdano** [comment]
As I said, it just won't work this way. The password value is ignored by Para as it is marked `transient`. Your user is created but the hash is blank or null. The code above should look like this:
```
public User createDefaultUserBean(ScooldUtils utils) {
	ParaClient pc = utils.getParaClient();
	User defaultUser = pc.signIn("password", "default@default.test::password");
	return defaultUser;
}
```

**Comment by mattcopas** [comment]
Have updated my bean to this:

String email = "default@default.test";
		User defaultUser = new User();
		defaultUser.setIdentifier(email);
		defaultUser.setPassword("password");
		defaultUser.setEmail(email);
		defaultUser.setActive(true);
		pc.create(defaultUser);

		User signedInUser = pc.signIn("password", "default@default.test::password");
		return signedInUser;

signInUser is still coming back as null, however...

**Comment by albogdano** [comment]
No, just get rid of all that initialization code and leave the 2 lines below.
