### ISSUE TITLE
403 – Invalid signature for request GET

### ISSUE THREAD

**Issue by utkarshsystem** [Erudika/para#187]
ParaClient connection throwing error
Failed to execute signed GET request to /v1/settings: 403 – Invalid signature for request GET /v1/settings coming from app paraLike
[just now](https://paraio.com/support#!/general:paraclient-connection-throw/paraclient-pc-new-paracli) i
ParaClient pc = new ParaClient(accessKey, secretKey);

// Para endpoint – [localhost:8080](http://localhost:8080/) or [paraio.com](https://paraio.com/)

pc.setEndpoint(paraServerURL);

// Set this to true if you want ParaClient to throw exceptions on HTTP errors

pc.throwExceptionOnHTTPError(false);

// send a test request – this should return a JSON object of type ‘app’

pc.me();

pc.me throwing error

Failed to execute signed GET request to /v1/settings: 403 – Invalid signature for request GET /v1/settings coming from app paraLike

**Comment by albogdano** [comment]
Are you trying to connect to the root app `app:para`? Did you initialize Para properly? Are there any errors in Para logs?

**Comment by utkarshsystem** [comment]
Yes I am trying to connect with the root para and the console works fine.
app:para
SecretKey: ****************************** works with console
Endpoint: ******************************* works with console

**Comment by utkarshsystem** [comment]
System.out.println("AppSettings .." + pc.appSettings());
		System.out.println("Para API Path .." + pc.getApiPath());
		System.out.println("Para Server version .." + pc.getServerVersion());
Endpoint: We have configured end point without v1

AppSettings ..{}
Para API Path ../v1/
Para Server version ..1.47.2

**Comment by utkarshsystem** [comment]
These are the debug logs

2022-12-14 20:39:13.534[0;39m [32mDEBUG[0;39m [35m24696[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.erudika.para.client.ParaClient      [0;39m [2m:[0;39m GET /v1/_settings, params: null
AppSettings ..{}
Para AI Path ../v1/
[2m2022-12-14 20:39:13.744[0;39m [32mDEBUG[0;39m [35m24696[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.erudika.para.client.ParaClient      [0;39m [2m:[0;39m GET /v1/, params: null
Para Server version ..1.47.2
[2m2022-12-14 20:39:13.868[0;39m [32mDEBUG[0;39m [35m24696[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.erudika.para.client.ParaClient      [0;39m [2m:[0;39m GET /v1/_me, params: null

**Comment by utkarshsystem** [comment]
It is working now but I have to add a dependency
<dependency>
    		<groupId>io.github.classgraph</groupId>
    		<artifactId>classgraph</artifactId>
    		<version>4.8.152</version>
		</dependency>
