### ISSUE TITLE
[WARN ] org.elasticsearch.indices.IndexAlreadyExistsException: already exists

### ISSUE THREAD

**Issue by lucav** [Erudika/para#2]
I'm using the android client sdk.
I have initialized the ParaClient with the secret key for testing purpose.
I attach the para.log and para-access.log.

[para.txt](https://github.com/Erudika/para/files/121922/para.txt)
[para-access.txt](https://github.com/Erudika/para/files/121919/para-access.txt)

**Comment by albogdano** [comment]
Luca, it appears that there are two instances of Elastisearch running at the same time on the same host. I think this is the cause of this error.

**Comment by lucav** [comment]
How could be possible?  
I'm sure on my server is running only one instance of Para server and Elastisearch should start automatically once.

**Comment by lucav** [comment]
Elastisearch should listen on port 9200 ?

**Comment by albogdano** [comment]
Yes, only 9200 and 9300 I think. Are you setting any other Elasticsearch configuration parameters like replica count? My guess is you have a local server running and the code is starting it's own embedded server which it shouldn't... I'll check.

**Comment by albogdano** [comment]
You are in "development" mode which means Para will look for Elasticsearch running on `http://localhost:9200`

**Comment by lucav** [comment]
Ok, after some investigations, i see that on Para server start the `Elasticsearch` doesn't start immediately but is waiting for "some" specific search queries from the api call (i don't know exactly what type of queries but for example `nearby` for sure).
If there is only one query in queue, it's ok, only one instance is created on port 9200.
But if there are more then one query in rapid sequence (because all api calls are `async`), then more then one instance is created on port 9200, 9201, 9202, and so on.
Have i explained good the problem

**Comment by albogdano** [comment]
Yes, so you aren't running two instances, but are you starting Elasticsearch separately/manually?

**Comment by lucav** [comment]
No, i don't start that manually, and i run only one instance of Para server. 
I try to explain better the flow:

- First, i start the Para server on my linux server only once, i see from `netstat -atnp` (linux command to see what process listen on what port) that it's listening on port 8080, i don't see any process listening on port 9200 or similar, so i think that Elasticsearch is NOT started yet, from the para.log file i see: 
`[INFO ] Started ParaServer in 4.807 seconds (JVM running for 9.697)`

- So, i start my android app that using the android client sdk for connecting with Para server. 
My app need to launch some queries on startup (in rapid sequence).
For example, my app call the following api call on startup (i write here the para-access.log entries, but i'm using the android client sdk):
1- "/v1/_me" (for testing connection)
2- "/v1/search/nearby?desc=true&latlng=0.0%2C0.0&limit=1000&page=1&q=%2A&radius=1&sort=timestamp&type=Locations" 
3- "/v1/search/terms?desc=true&limit=1&matchall=true&page=1&sort=timestamp&terms=emailAccount%3Atest%40gmail.com&type=Lic"

These 3 api calls are done in very few time, you know because are async calls, the android client don't wait for a response and immediately go to the next line of code. In some milliseconds my app call these.
So, now what happens on Para server?
I see from `netstat -atnp` that some process listen on ports 9200, 9201 (but how many ports/process are listeing on ports 920X depends on how many queries are done the first time).
From para.log file i see:
`
2016-02-10 13:07:25,415 [INFO ] [para-es-1] initialized
2016-02-10 13:07:25,418 [INFO ] [para-es-1] initialized
2016-02-10 13:07:25,424 [INFO ] [para-es-1] starting ...
2016-02-10 13:07:25,425 [INFO ] [para-es-1] starting ...
2016-02-10 13:07:25,429 [INFO ] [para-es-1] publish_address {local[1]}, bound_addresses {local[1]}
2016-02-10 13:07:25,433 [INFO ] [para-es-1] publish_address {local[2]}, bound_addresses {local[2]}
2016-02-10 13:07:25,444 [INFO ] [para-es-1] para-dev/kN1oCXtbS1S8_RYGWyPuqQ
2016-02-10 13:07:25,447 [INFO ] [para-es-1] master {new {para-es-1}{kN1oCXtbS1S8_RYGWyPuqQ}{local}{local[2]}{local=true}}, removed {{para-es-1}{5XWuNmjNSrunidr9ttPLHQ}{local}{local[2]}{local=true},}, added {{para-es-1}{gg-y3HueTp6ryyD9II5z-A}{local}{local[1]}{local=true},}, reason: local-disco-initial_connect(master)
2016-02-10 13:07:25,448 [INFO ] [para-es-1] para-dev/gg-y3HueTp6ryyD9II5z-A
2016-02-10 13:07:25,455 [INFO ] [para-es-1] master {new {para-es-1}{kN1oCXtbS1S8_RYGWyPuqQ}{local}{local[2]}{local=true}}, removed {{para-es-1}{d0Nev0pnTPyU5VRInbDjGQ}{local}{local[1]}{local=true},}, added {{para-es-1}{kN1oCXtbS1S8_RYGWyPuqQ}{local}{local[2]}{local=true},}, reason: local-disco-receive(from master)
2016-02-10 13:07:25,705 [INFO ] [para-es-1] publish_address {127.0.0.1:9201}, bound_addresses {127.0.0.1:9201}, {[::1]:9201}
2016-02-10 13:07:25,706 [INFO ] [para-es-1] started
2016-02-10 13:07:25,706 [INFO ] [para-es-1] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
2016-02-10 13:07:25,714 [INFO ] [para-es-1] started
`

I think, if Elasticsearch is not started yet, at the first search query the Elasticsearch start.
Is it right?

First search query arrive -> Elasticsearch 1 on starting -> Second search query arrive -> Elasticsearch 1 is NOT started yet (because take some time) -> Elasticsearch 2 on starting -> Elasticsearch 1 is started -> Elasticsearch 2 is started.

**Comment by lucav** [comment]
I think the solution could be to start Elasticsearch when the Para server start, so the Elasticsearch will start only once.

**Comment by albogdano** [comment]
OK, so if the problem is Elasticsearch not starting with Para, then this is easy to solve. I can add an option like `para.es.lazy_start = false` to turn off the lazy initialization of the ES client. At the moment ES starts only after you try to use it. I was worried that maybe something else is broken. Are you OK with this option? If the exception still appears then we need to debug this.

**Comment by lucav** [comment]
Ok, it's working perfectly! Great!

**Comment by albogdano** [comment]
:+1: Thanks for closing this.
