### ISSUE TITLE
How to do aggregation query?

### ISSUE THREAD

**Issue by jg506** [Erudika/para#23]
Hi,

Is there any way to do aggregation query such as sum of values?

Regards,
Jon

**Comment by albogdano** [comment]
Hi Jon, only counting results is currently possible. Can you give me an example of an aggregation query?

**Comment by albogdano** [comment]
This is now supported through the new Elasticsearch proxy endpoint `/v1/_elasticsearch`. This endpoint gives you direct access to Elasticsearch and you can send any request to it using ParaClient. For example:
```java
Response res = paraClient.invokePost("_elasticsearch?path=_search", Entity.json("{ your_query }"));
```
