### ISSUE TITLE
Implement some basic metrics using DropWizard Metrics

### ISSUE THREAD

**Issue by albogdano** [Erudika/para#27]
- [ ] Metric for latency
- [ ] Metric for counting stuff

... suggestions are welcome

**Comment by jswiesner** [comment]
I've been thinking about the implementation of this, and I wanted to share my initial thoughts for feedback. Let me know what you think.

# Setup
The DropWizard Timer (records count plus duration) will be the primary mechanism for capturing metrics. A new singleton class called MetricsUtils in para-core will serve as a centralized utility for creating and managing all DropWizard timers. There will be a MetricsRegistry for each app and each class in Para, which is managed by the DropWizard SharedMetricsRegistries class. SharedMetricsRegistries is basically just a concurrent hash map which holds onto all the MetricsRegistry objects in use. MetricsUtils will hold access to the SharedMetricsRegistries, and any method that wants to initiate timing will call a singleton method on MetricsUtils to return a new Timer.Context object for that unique app + class + method. 

Every application making calls to Para will have its own metrics recorded. Simultaneously, system-wide metrics will also be recorded. So when an application makes a call to a timed method, there will be two Timer.Context objects instantiated for recording the count and duration of that method. The first timer captures the system-wide metrics, as it includes every call to this method across all applications. The second context is custom to the application that made the request so metrics can be evaluated for an individual application.

The Timer.Context objects are consumed in code with Java's try-with-resources blocks. The try-with-resources block will invoke a call to MetricsUtil that starts both needed Timer.Context objects (application-specific and system wide). The completion of the try-with-resources block will close both context objects. 

MetricsUtils also serves as the centralized place to get the actual metrics data. Metrics are always recorded, both for the entire system and for each application, but the user can decide how, if at all, the metrics are reported. 

# Recording
Once MetricsUtils is written, it will be very easy to add timers throughout the code. Ideally, we would like fine grained timers around all database, search and cache operations. It would also be useful to see the overall time of a broad operation (such as findTerms(), for example), but it would also be useful to see how much of that time is consumed in each operation that Para manages. A user should be able to understand the time spent in findTerms, but also see how much of that time is consumed by database operations, search indexing, caching, and Para overhead. 

It's clear that we would like to avoid requiring every DAO, Search and Cache implementation to implement their own timers. Avoiding this might be as simple as implementing timers through AOP in the IndexAndCacheAspect class. In the invoke() method, a timer can be added to encapsulate the DAO, Search and Cache calls. The class and method names for each DAO, Search and Cache implementation can be inferred to retrieve the appropriate timer for each request. It's also worthwhile to time the RESTful end points to capture the number of requests to each method, and record the total time to fulfill each request.

# Publishing
For the first implementation, system metrics statistics are available in two ways. First, the system-wide metrics can be optionally saved to the Para log file with a user-defined frequency. A new environment variable called "para.metrics.logging_rate", which defaults to 0 (disabled), specifies the number of seconds between metrics writes to the log. The second way to query the system-wide metrics is to make a GET request to a new RESTful end point at /v1/_metrics. This allows external systems to query real-time metrics for the system as needed. The application-specific metrics will only be available through a RESTful end point at /v1/appid/_metrics.

Later we can add more advanced features for reporting metrics to support a push mechanism, such as publishing to Graphite. In this case a user could specify settings about the server running Graphite that can receive metrics data at a rate prescribed by the user. This would make it easy to setup a Grafana dashboard, for example, to visualize all metrics for the Para server - both for the whole system and for specific applications.

**Comment by albogdano** [comment]
Well written! I really like this implementation strategy. There's one detail about the RESTful endpoint - due to the fact that apps are isolated from each other, calling `/v1/_metrics` will always return the metrics in the context of the app that's calling that endpoint. It is bound to the access+secret keys to that app or a JWT token with the `appid`. Now, there's the concept of a "root app" which keeps track of all other apps and it can store the system-wide metrics but these will only be accessible with the root app credentials, again via `/v1/_metrics`. You'll also notice that the `appid` doesn't appear anywhere in the API resource paths after `/v1/...` because of the same reason that we get it through the `Authorization` header.

**Comment by jswiesner** [comment]
That makes sense, thanks for the feedback! I overlooked the appid inherently encoded in the request. I agree that returning system metrics for the root application is the most logical. We have two options then when initiating a timer when the request is peformed by the root app. Would you prefer to still record timing data for the root app itself? Or when the root app is making the request, the alternative is to just iniaite the system-wide timer. 

I will start with implementing timers on the DAO, Search and Cache implementations using the AOP approach I mentioned above. What are your thoughts about timing the REST end points? We could add timers in the RestUtils class directly on all the noteworthy methods (CRUD + search), but an alternative approach is to add another AOP aspect that binds to all the REST methods to simplify the implementation here as well. The latter approach may end up with an overwhelming amount of metrics data though, so I’m not sure it’s necessarily better. What are your thoughts on this?

**Comment by albogdano** [comment]
I think it's better to record metrics for the root app itself, I mean it's still an app like the others and also there's the possibility that some people may want to run a single-tenant server with only one app - the root app. They might want to see the metrics for it just like for any other app.

The AOP class is the best place for initiating metrics as most operation go through it. As for the REST methods, I saw there's a `AbstractInstrumentedFilter` inside **metrics-servlet**, perhaps it might be used to automatically monitor each request, or a custom servlet filter could also be created. One good place to add metrics for REST methods is the `GenericExceptionMapper` class. It catches exceptions and transforms them into JSON responses. But I think just adding a few timers around the CRUD methods in `RestUtils` would be just great for now.

**Comment by jswiesner** [comment]
I just briefly looked at the metrics-servlet module and that looks like the way to go for measuring REST requests. So to start I’ll implement timers around the DAO, search and cache AOP aspects and around the key methods in RestUtils. I’m thinking it would be useful to also leverage the DropWizard heath check and expose it at /v1/_health. The health check should return the same response for any application requesting it. The health check could be as simple as pulling some known document from the DB, search and cache (if active), and comparing the objects for equivalence. If you could pull the app object from all 3 sources (which indicates the sources are active and working), and they all properly return the same object, that’s a good simple indication the system is healthy. 

So what should be the expected response for /v1/_metrics when made by the root app? Should that be the application metrics for the root app itself, or the system metrics? I suppose for consistency it should return the metrics for the root app only. In that case, maybe the system metrics are only available through the log file.

**Comment by albogdano** [comment]
The health endpoint is also a good idea. `/v1/_health` or `/v1/_metrics/health` ? It's up to you, both look good to me. Can the root app metrics include both system metrics and the actual metrics for the root app itself? If not, just returning the system metrics would be enough I think. If we keep the consistency and show only the root app metrics, how are we going to get the system metrics? `/v1/_metrics/system` is one option where you have a check `app.isRootApp()` or `App.isRoot(appid)`.

**Comment by jswiesner** [comment]
@albogdano if you have some time, you're welcome to review the WIP metrics implementation [here](https://github.com/jswiesner/para/tree/metrics). The work is in the 'metrics' branch of my Para fork. Any feedback you have would be much appreciated.

I added timers around all the individual DAO, search and cache methods. I also added timers to the REST endpoints for CRUD (serial and batch), links, search and custom resource handlers. Right now I've set it up to record metrics for the entire system as well as each individual application. The timers on the individual DAO, search and cache methods means you can see the total latency of your REST calls, but also the breakdown of each individual operation.

Right now the metrics are set up to write the overall system metrics to a log file called para-metric.log every minute. I'll add this frequency as a user-configured option. 

I have a few questions for you:

1. I need a name for the default system metrics that is distinct from every application name. For now I chose "_system", but if it's possible for someone to create an app named "_system" then this would be problematic. If this name isn't sufficient, are there any that you know of that will ensure uniqueness against any possible user-defined application name?

2. I added timers around all the custom resource handlers in the Api1 class. I need to know the appid that invoked the custom handler, but for now I simply left it hardwired as "appid". How can I cleanly get the appid from the ContainerRequestContext (see here: https://github.com/jswiesner/para/blob/55e20414dd9dc7697b18f8632dda5f49995cf6e4/para-server/src/main/java/com/erudika/para/rest/Api1.java#L187). I saw you are already doing this in the Elasticsearch plugin to decipher the caller of the proxy endpoint, but the code to get the appid is pretty lengthy and I'd prefer not duplicate the same code.

3. The metrics are working, but for now the metrics are only reported after the timer is called for the first time. I need to add some code to initialize all the possible timers for each application so from the moment the server starts it will begin reporting 0s for all the timers. For this, I'll need to know all the existing applications when the static block is executed in MetricsUtil. Is there a way for me to query all existing applications at this point of initialization?

**Comment by albogdano** [comment]
Well done! 
1. App ids cannot contain special chars except for "-" so "_system" should be fine
2. Have a look at [ProxyResourceHandler.java](https://github.com/Erudika/para-search-elasticsearch/blob/master/src/main/java/com/erudika/para/rest/ProxyResourceHandler.java#L143). I think I'll move that method to `Utils` in para-core so it's easily accessible from everywhere. It parses the Authorization header - it contains either a JSON web token (bearer) or AWS signature 
3. I'll think about this one and come back to it later.

**Comment by jswiesner** [comment]
For #3 I’m thinking this may not be necessary after all. The absence of a particular metric from the log implies zero count and latency. I could initialize all the known metrics, but since we will capture metrics on custom resource handlers too there is no way to know ahead all the possible timers that need to be initialized. What do you think about this?

**Comment by albogdano** [comment]
Yes, I think it's best if we don't query the database for all apps on startup. How exactly do you initialize a know metric? Is it just that try-with-resources block or something else? 
You can also choose to register several event listeners and do something on startup/shutdown or whenever an app is created/deleted:
```
Para.addInitListener(new InitializeListener() 
  public void onInitialize() {
    // startup
  }
});
Para.addDestroyListener(new DestroyListener() 
  public void onDestroy() {
    // shutdown
  }
});
App.addAppCreatedListener(new AppCreatedListener() {
   public void onAppCreated(App app) {
     // app created
   }
});
App.addAppCreatedListener(new AppCreatedListener() {
   public void onAppCreated(App app) {
     // app deleted
   }
});
```

**Comment by jswiesner** [comment]
You can initialize a metric by simply creating the DropWizard Timer object at startup. Otherwise it will only create the Timer object when you make the first call to initiate a timing. There is definitely value to doing this initialization, but it only seems problematic for the custom resource handlers. We know about the custom resource handlers during init, right? If so, I probably could just initialize these as well without problem.

Does addInitListener get called once for the entire application, or does it get called for each individual application? And for the app created listener, does it get called when Para loads existing apps during init, or only the very first time an app is created? To do the metrics initialization properly we would need to know about all existing applications when we start up the server, and then we can just initialize all new app metrics on the fly as the apps are created.

**Comment by jswiesner** [comment]
I just looked back at Api1 and it won’t be a problem to init metrics on custom resource handlers. The only problem I need to solve is how to get the apps that already exist when Para Server is starting up.

**Comment by albogdano** [comment]
So `addInitListener()` is called once when Para is initialized i.e. `Para.initialize()` is called. It is called exactly once when you start Para as JAR/WAR or you embed it in your code and initialize it manually. It has nothing to do with Para apps. App listeners and only for when a new app is created or an existing one is deleted. 
Yes, custom handlers are loaded once on startup and Api1 knows everything about them. So in order to get all apps on startup you'll have to search for them with something like `Para.getSearch().findQuery("app", "*", new Pager(10000));`
