### ISSUE TITLE
MockSearch issue para-core 1.50.3 - 

### ISSUE THREAD

**Issue by Sree-Durga-G** [Erudika/para#304]
MockSearch issue : Running the jar file inside the target folder of para-jar. Unable to resolve the issue. Kindly find the attached screenshot
![image (1)](https://github.com/user-attachments/assets/b32de8e9-4628-48f5-978c-8fce57f52e26)

**Comment by albogdano** [comment]
Edit or remove the `para-application.conf` file. Here's a sample configuration:
```ini
# Default configuration file for Para
para.env = "production"
para.dao = "H2DAO"
para.search = "LuceneSearch"

```

**Comment by albogdano** [comment]
Download the JAR file from here: https://paraio.org

**Comment by Sree-Durga-G** [comment]
Used the below configuration 
**para-application.conf** file

# Default configuration file for Para
para.env = "production"
para.dao = "H2DAO"
para.search = "LuceneSearch"
Logs attached below 
![image](https://github.com/user-attachments/assets/0f192e53-ec7e-4304-ae18-a76c2dca5884)

As we are using ElasticSearch I have changed the para.search = "ElasticSearch" Getting same MockSearch issue. Attaching the logs
![image](https://github.com/user-attachments/assets/bae01667-9728-4a27-a660-1b7573719efa)

**Comment by albogdano** [comment]
You need to add the `para-search-elasticsearch` plugin from [Erudika/para-search-elasticsearch](https://github.com/Erudika/para-search-elasticsearch/releases/tag/1.41.3)  and add the JAR to the `./lib` folder next to para.jar

**Comment by Sree-Durga-G** [comment]
Hi. I have downloaded and added the jar inside the lib folder in para-jar. The issue has been resolved. However, could you please share the proper dependency that needs to be added in para-jar?

**Comment by albogdano** [comment]
@Sree-Durga-G There is nothing else you need to add. You just need the `para-jar-1.50.3.jar` file and the `./lib/para-search-elasticsearch.jar` in the lib folder. Then you start Para from the JAR file. You don't have to recompile anything.
