### ISSUE TITLE
Some Microsoft users cannot authenticate (Scoold/Para)

### ISSUE THREAD

**Issue by alexvillalta** [Erudika/para#37]
I am trying to register users via Microsoft authentication on a Scoold site running with Para, but some of them get authentication errors although they have valid Microsoft accounts.

For reference, I am running v1.28.5 of the executable Para WAR file on localhost:8080, and then using it as the backend for a [Scoold](https://github.com/Erudika/scoold/) instance also running on localhost.

I would first try registering a user with their Microsoft account; for the affected Microsoft accounts, the user either: 
1. gets stuck on the Microsoft login screen as they wait for Para to redirect them back to the Scoold site, or
2. they are redirected, but get an "Authentication failed" error. 

In the first case, the Para server stops logging in any users, including those that had no issues before. I then have to restart the Para server to log/register users again. When I terminate the process, I get this [stack trace](https://github.com/Erudika/para/files/1813498/stack_trace.txt).

In the second case, the Para server continues working fine for users with unaffected Microsoft accounts, and Para just logs the following error (seems to come from MicrosoftAuthFilter.java and SecurityUtils.java:)
`2018-03-14 15:40:50 ←[1;31m[ERROR]←[0;39m Bad credentials.`

In both cases, no new user objects are created on Para, and I have not been able to find why one case happens instead of the other.

After some testing, I did find that older Microsoft accounts (created before July 2017) did not cause any problems, while newer Microsoft accounts (created within the last week) tended to trigger the issue (note, though, this is based on testing only a handful of Microsoft accounts; I will post any updates if I can further isolate the issue.)

**Comment by albogdano** [comment]
After some investigation, I found that cause of this issue is a slow response from https://graph.microsoft.com/v1.0/me endpoint. The code itself is valid and works fine, but it works only when that enpoint respons within 15-20 seconds.

Now, for newer accounts there's a different issue. I also tried creating a new Live account and it failed with this very cryptic message:
```
{
  code=RetryWithPuid, 
  message=Please retry With PUID in either token or URL, 
  innerError={ request-id=7b022e74-a054-4aec-8d3d-e2713fbb3a6d, date=2018-03-13T18:09:15 }
}
```
Then I tried clicking around my account and opened the Mail app (Outlook online) and also Skype through the browser. This somehow activated my account and I was then able to login on https://live.scoold.com.

I'm not sure there's anything I'm able to do about this. It's a problem on the side of Microsoft, rather than Para.

**Comment by alexvillalta** [comment]
Thanks Alex; it does sound like it is a Microsoft issue in that case. Others are getting this error too (see this [thread](https://stackoverflow.com/questions/49284516/microsoft-graph-api-is-returning-unknownerror-for-msa-users) from StackOverflow.) I'll wait for now to see if Microsoft fixes it on their end before looking for workarounds.

**Comment by albogdano** [comment]
This appears to have been fixed now. See #38.

**Comment by alexvillalta** [comment]
Hi Alex; apologies for the late reply. I just tested this out with the latest version of Para, and it worked. Has this change also been carried over into paraio.com? Thanks,

**Comment by albogdano** [comment]
@alexvillalta Yes, the change is deployed to Paraio.com as well.

**Comment by alexvillalta** [comment]
Excellent! Thanks a lot
