### ISSUE TITLE
Support for third-party OAuth providers ?

### ISSUE THREAD

**Issue by bcopy** [Erudika/para#4]
Hello,

My organization already provides an OAuth authorization service. However, I can't seem to see how to integrate Para with it - the doc says that OpenID is deprecated and to use OAuth instead, but then it only lists Facebook, Github etc.... but there is no entry for generic OAuth support.

Can you tell me if OAuth is supported ?

**Comment by albogdano** [comment]
Hi, yes the Openid implementation uses the old standard which is different from OpenID Connect. Maybe the docs are a bit unclear in this regard - OAuth is used for authenticating with Facebook, Google, etc. Currently the only way to integrate with another identity provider is to write a new authentication filter. Are you using OpenID connect at all or just want to integrate with your own service?

**Comment by bcopy** [comment]
It's actually OAuth and it's our own infrastructure and servers

**Comment by albogdano** [comment]
Ok. It can be made possible for auth filters to be loaded as plugins if you are willing to write it yourself. Another option would be to have like a generic OAuth2 filter implemenation but from what I've seen it won't work for all, as there are subtle differences in parameters and flows.

**Comment by bcopy** [comment]
Ah ok I thought Oauth2 was standard, we've integrated with Spring security
and SharePoint without any significant issue.

**Comment by albogdano** [comment]
It is a standard, yes. But for example, with Facebook you have make a `GET` request first to get an auth code and with Google it must be a `POST` request. It could be problematic, i.e. it might work for you but be broken for other peoples OAuth services. Para uses Spring Security too, so it would take about 200 lines of Java code to make the integration. I can post the code here, later today.

**Comment by bcopy** [comment]
Yes apparently Facebook are not playing by the rules :
http://stackoverflow.com/questions/8274819/should-clients-get-oauth-2-access-tokens-using-get-or-post

I can confirm our Microsoft Active Directory / Shibboleth infrastructure
uses a POST request. I should hope most implementations will follow the
RFCs.

**Comment by albogdano** [comment]
So here's the Gist I've created - a generic filter for integrating with an OAuth 2.0 service. Take a look: https://gist.github.com/albogdano/808e26d337f1a4b9fb4d82754d24491c

**Comment by albogdano** [comment]
I've updated the code and it will be included in the next version of Para. Suggestions and feedback is appreciated.
