### ISSUE TITLE
How to use para to connect to DynamoDB?

### ISSUE THREAD

**Issue by ramswaroop** [Erudika/para#43]
If all that is required is to set some properties then a list of properties to set in `application.conf` file would be great.

**Comment by albogdano** [comment]
You don't have to configure anything except `para.dao = "AWSDynamoDAO"`. If you start DynamoDB locally it will connect to it on port 8000. See http://paraio.org/docs/#013-dynamodb

**Comment by ramswaroop** [comment]
I think what you are saying is for DynamoDB run locally but what if I want to use the DynomoDb Web service i.e, para running in an EC2 instance and a DynomoDB spun separately under the same AWS account?

**Comment by albogdano** [comment]
In an AWS environment the DynamoDB service is automatically detected and Para will connect to it.

**Comment by ramswaroop** [comment]
Thanks, @albogdano, nice to know this.
