### ISSUE TITLE
Request rebuild index feature

### ISSUE THREAD

**Issue by ensecoz** [Erudika/para#45]
Ability to rebuild index for ES and Lucene. (also add support this rebuild from para-cli)

Use case#1: Migrate search layer from lucene to ES
Use case#2: Restore db from backup and the index is not sync between Search Index and Sql DB
Use case#3: The index might be corrupted somehow and it is nice if we can rebuild index from database

**Comment by albogdano** [comment]
You can rebuild the index by calling `search.rebuildIndex()`, it's just not exposed through the API yet.
