### ISSUE TITLE
docker :latest tag missing

### ISSUE THREAD

**Issue by weisjohn** [Erudika/para#48]
This fails:

```
λ docker pull erudikaltd/para
Using default tag: latest
Error response from daemon: manifest for erudikaltd/para:latest not found
```

Based on the tags published at https://hub.docker.com/r/erudikaltd/para/tags/ , this succeeds:

```
λ docker pull erudikaltd/para:v1.29.2
v1.29.2: Pulling from erudikaltd/para
```

Someone should publish an untagged / latest image for the sake of the documentation.

**Comment by albogdano** [comment]
Done.

**Comment by weisjohn** [comment]
@albogdano thanks!
