### ISSUE TITLE
Support for images / files

### ISSUE THREAD

**Issue by sivapattabhiram** [Erudika/para#5]
Does Para support upload of images / files and attaching them to objects - something equivalent to the concept of assets in usergrid / baasbox?

**Comment by albogdano** [comment]
There is some rudimentary support for file uploads through the `FileStore` interface. It's implemented only for AWS S3 at the moment. This functionality is left for a future release. There's nothing stopping you to attach file links to objects right now.

**Comment by sivapattabhiram** [comment]
Okay. Thanks.
