### ISSUE TITLE
Can only access Para on localhost

### ISSUE THREAD

**Issue by wleev** [Erudika/para#52]
I've been trying to set up Para on a test server and mapping it with Nginx and a reverse proxy, but neither Scoold nor para-cli can acces it on the public ip. Accessing it through localhost works fine however.

Endpoints like `/v1/_setup` however work with the public ip. I've tried both Nginx and running it directly on an open port.

Config I'm using for Nginx:
```
server {
       listen 32461 http2;
       listen [::]:32461 http2;

       location / {
        proxy_pass       http://localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
       }
}
```

Logs are not giving me anything informative either, any idea where I can start debugging?

**Comment by albogdano** [comment]
I'm not an nginx expert but it seems like a firewall issue. Is that the whole configuration or just part of it. What is the value of `server_name`? How about `listen *:32461 http2;` - does it help?

**Comment by wleev** [comment]
I'm using public IP to access the server, so I think I can skip server_name. I tried it with a subdomain before, but that didn't work either.

What endpoint does `para-cli ping` hit? Maybe I can start investigating from there.

**Comment by albogdano** [comment]
By default `para-cli` will connect to https://paraio.com but you can run `para-cli setup` to change that (or just edit the `para-cli` config file)

**Comment by wleev** [comment]
I can setup para-cli with localhost, but not with the public IP. What URLs are being called during setup/ping? I can check if there's anything wrong with those since '/v1/_setup' is accessible in a browser. Seems like a weird issue seeing it's partially working, I'd expect more of an all or nothing situation in case of a bad nginx config.

**Comment by albogdano** [comment]
Hm, yea it is kinda strange. The ping URL is `GET /v1/_me` and `para-cli setup` just configures the CLI tool to connect to a specific Para server, but it doesn't call `/v1/_setup` automatically. That is only needed to initialize the Para server. The CLI config file is located somewhere in your home directory.

**Comment by wleev** [comment]
Sorry for the delay, but after some quick testing I found out the `/v1/_me` URL isn't working, while the `/v1/_setup` URL works just fine. Anything off the top of your head that you think might be causing this?

**Comment by wleev** [comment]
This has been fixed, error on my part due to a mix-up of keys and my dev server lacking outbound access.

Thanks for the support, it helped me narrow down the cause.
