### ISSUE TITLE
OAuth redirect_uri not using HTTPS

### ISSUE THREAD

**Issue by wleev** [Erudika/para#54]
I've recently upgraded my services to support HTTPS, but since then my OAuth2 authorization won't work anymore. After some digging, I found out that para still sends the `http` version of the url to my endpoint instead of the `https` one. I could allow the `http` redirect on my authorization server, but am wondering what I could be missing in the configurations.

In the scoold application.conf the Para endpoint is set to the 'https://' version and in Para the environment is set to 'production'. Is there anything else I might be missing?

**Comment by albogdano** [comment]
Are you talking about `GenericOAuth2Filter`? And also, which redirect do you mean - is it the redirect from the IDP back to Para or the redirect from Para to the URL specified in `para.security.signin_success`?

**Comment by wleev** [comment]
IDP back to Para. The one resembling this `http://domain.com/oauth2_auth`.

**Comment by albogdano** [comment]
That URL should start with `https://`. When redirecting the user to IDP you specify the `redirect_url` which points to Para and it should be something like `https://domain.com/oauth2_auth`. In other words, Para should be deployed with HTTPS enabled.

**Comment by wleev** [comment]
Yes, that's what I was expecting to happen to. I currently have nginx setup with HTTPS enabled and a proxy redirect enabled like in the example in the Para docs. But it seems Para internally doesn't realize it's on HTTPS, and I haven't seen a case of being able to force the `redirect_url` in the docs yet. Maybe I'm missing something in my nginx config.

```
server {
    server_name domain.com;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header X-Real-Ip $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    add_header Strict-Transport-Security max-age=15768000;
    ssl_stapling on;
    ssl_stapling_verify on;
}
server {
    if ($host = domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name  domain.com;
    return 404; # managed by Certbot
}
```

**Comment by albogdano** [comment]
Ah, ok! I see that you are setting the `X-Forwarded-For` header but you need to set `X-Forwarded-Proto` to `https` as well. Try adding that header after `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`

**Comment by wleev** [comment]
That did the trick! Maybe it would be best to add that to the sample nginx config in the Para docs.

**Comment by albogdano** [comment]
Yes, I'll add that line to the example config in the docs. :+1:
