### ISSUE TITLE
how to run this project in idea

### ISSUE THREAD

**Issue by yuchangfu** [Erudika/para#57]
how to run this project in idea

**Comment by yuchangfu** [comment]
I run with doc command mvn -Dconfig.file=./application.conf spring-boot:run
and got error this:
**ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/yuchangfu/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException**

how to fix it???

**Comment by albogdano** [comment]
You'll have to run that command from the `./para-server` directory. Open the `para-server` subproject and run the command on it.

**Comment by albogdano** [comment]
Now, you can also run `mvn spring-boot:run` from the `./para-jar` folder. Just pull from master first.

**Comment by yuchangfu** [comment]
thank you . work perfect
