### ISSUE TITLE
Image doesn't work on Linux

### ISSUE THREAD

**Issue by MrFireman** [Erudika/para#6]
Whenever I try to deploy the image on a CentOS7 or Ubuntu (DigitalOcean) the project runs, but the specific url of the secret key ( localhost:8080/v1/_setup ) is not giving back any answer back. (Though the  localhost:8080/v1/   gives back no permission error)

 I tried to recompile it from source, also I ran it with OpenJDK and Oracle, and the result was always the same.

 On Mac and Windows the .war file is working properly.

**Comment by albogdano** [comment]
Are you deploying it as it is, i.e., no configuration changes or connection to a database? It's possible that an exception is thrown and it is logged somewhere.. I've just created a DigitalOcean account to try and replicate this.

**Comment by MrFireman** [comment]
Yeah I just started without any additional configuration, without any DB set up. It works well on other Ooperating systems in the same way. Were you able to replicate the issue?

**Comment by albogdano** [comment]
Yeah, I was able to replicate it, sorta.. It works but takes forever to create the index on that tiny 5$ droplet. Try to wait about 2-3 minutes without closing the connection. To reset everything, just delete the "data" folder next to the .war file.

**Comment by MrFireman** [comment]
Yeah, it doesn't appear to be working, even on the $40 server. Do you have any advise what service to use instead of DigitalOcean, where I could host this? Thanks

**Comment by albogdano** [comment]
You mean it doesn't work at all, or it just initializes slowly on all droplets? It seems odd to me how the 40$ one is still slow but then again I have no experience with DigitalOcean. You could try Heroku or AWS, and I heard the new Google cloud is nice, too.
