### ISSUE TITLE
Logs and Verbosity

### ISSUE THREAD

**Issue by psybox** [Erudika/para#60]
There is any log level to set? It's running on 8080 and scoold on 8000 but I cant access and there are no errors or log messages about the access.

**Comment by albogdano** [comment]
When you start Para it will create 3 log files - `para.log`, `para-access.log` and `para-metrics.log` in the same directory. Check `para.log` for exceptions. How are you running Para - the standard way or using docker?

**Comment by psybox** [comment]
Ok I will check.
The standard way.
