### ISSUE TITLE
Python client for Para

### ISSUE THREAD

**Issue by kylemhall** [Erudika/para#66]
I was wondering if you have any plans on releasing a Python client for Para.

**Comment by albogdano** [comment]
The Python client is on the roadmap but it would take at least a couple of
months for it to be released. A realistic release date would be the middle
of December.

**Comment by kylemhall** [comment]
That's great news!

**Comment by albogdano** [comment]
**Update**: work in progress

**Comment by albogdano** [comment]
**Released!** 
`pip install paraclient`
- https://pypi.org/project/paraclient/
- https://github.com/Erudika/para-client-python
