### ISSUE TITLE
Increase logging verbosity?

### ISSUE THREAD

**Issue by heprotecbuthealsoattac** [Erudika/para#67]
Hi,
I can't find a way to increase the logging level in para, currently I'm trying to configure an OAuth2 authentication and getting back and error, however have no idea how to actually debug that issue because the error isn't shown anywhere, the only reason I know it exists is because I'm redirected to the para.fail_url (or whatever the name is).

**Comment by albogdano** [comment]
Para is a Spring Boot app so the standard Boot options apply: `-Dlogging.level.org.springframework=DEBUG` or similar system property would enable verbose logging on that package. 
The most common mistakes when configuring OAuth are - forgetting to whitelist the correct redirect URL with your OAuth provider and missing parameter name configuration which tell Para where to look for user data. 
I've recently improved logging for OAuth in commits 558b6d51 and a5600b6f

**Comment by heprotecbuthealsoattac** [comment]
That helps (not by much tho)! Thank you.
