### ISSUE TITLE
Configure OAuth2 login with Auth0

### ISSUE THREAD

**Issue by heprotecbuthealsoattac** [Erudika/para#68]
I configured OAuth2 with following options in scoold:

```
para.oa2_app_id = "<redacted>"
para.oa2_secret = "<redacted>"
para.security.oauth.authz_url = "https://myorg.auth0.com/authorize"
para.security.oauth.token_url = "https://myorg.auth0.com/oauth/token"
para.security.oauth.profile_url = "https://myorg.auth0.com/userinfo"
para.security.oauth.provider = "Log in"
```

however the sign fails every time and I get redirected to `https://<redacted>/signin?code=3&error=true`
![Screenshot from 2019-11-22 17-07-54](https://user-images.githubusercontent.com/52574745/69445662-abd7a980-0d4a-11ea-88a9-ff91ef83e0c8.png)

Here are the scoold logs
[scoold.log](https://github.com/Erudika/para/files/3880639/scoold.log)
and para logs
[para.log](https://github.com/Erudika/para/files/3880649/para.log)

Any idea how can I debug this issue further without  breadcrumb debugging?

**Comment by heprotecbuthealsoattac** [comment]
By the way, after clicking log in I do get redirected to an auth0 page however when I get redirected back to the backend I get this failure.

**Comment by albogdano** [comment]
You need to configure the parameter names for that userinfo response object. Start with `para.security.oauth.parameters.id` then `para.security.oauth.parameters.name` etc.

**Comment by heprotecbuthealsoattac** [comment]
I did that just now to no avail. The problem is that I'm in the dark, even though I've enabled TRACE logging. Tried setting para.security.oauth.scope para.security.oauth.parameters.id and others yet the result is exactly the same.

**Comment by albogdano** [comment]
Have you whitelisted the redirect URL `https://para_host:port/oauth2_auth` with Auth0?

**Comment by albogdano** [comment]
![image](https://user-images.githubusercontent.com/346873/69454979-194a0100-0d70-11ea-9305-c72b96c8752a.png)
This is what the authorization page should look like. The property `para.security.oauth.scope = "openid%20profile%20email"` is essential here.

**Comment by heprotecbuthealsoattac** [comment]
The master version does help a lot to debug this issue (it told me what was wrong exactly). Also in the docs it's not mentioned that `para.security.oauth.scope` should be url escaped. I did manage to get it to work finally, thank you for all the help!

**Comment by albogdano** [comment]
I'll update the docs now. Thank you!
