### ISSUE TITLE
Mongodb DAO incompatible with Linkedin connect

### ISSUE THREAD

**Issue by julienfr112** [Erudika/para#7]
v1.24.3 work great in embeded mode, but when using mongodb DAO, it doesn't work : 

When connecting with linkedin, the connection fail and the para gives this error ;

 `[WARN ] Cookie rejected [lang="v=2&lang=en-us", version:1, domain:linkedin.com, path:/, expiry:null] Domain attribute "linkedin.com" violates RFC 2109: domain must start with a dot
[WARN ] Cookie rejected [lang="v=2&lang=en-us", version:1, domain:linkedin.com, path:/, expiry:null] Domain attribute "linkedin.com" violates RFC 2109: domain must start with a dot
2017-05-14 00:57:56 [WARN ] Invalid cookie header: "Set-Cookie:`

Very very strange.

**Comment by albogdano** [comment]
This warning isn't related to Mongo plugin, is there anything else in the log that might help us?

**Comment by julienfr112** [comment]
I know it's unrelated, but i don't got it without the plugin, and i get it with the plugin, and linkedin login fail only in the second case ....

**Comment by albogdano** [comment]
I wasn't able to reproduce the problem. If you can pinpoint the cause or tell me how to reproduce it, I'll fix it.

**Comment by albogdano** [comment]
@connectometeam Try using the latest Para version 1.30.1 and MongoDB DAO plugin version 1.30.0.
