### ISSUE TITLE
How to get in touch about a security issue?

### ISSUE THREAD

**Issue by zidingz** [Erudika/para#78]
Hey there,

As there isn't a SECURITY.md or contact address in your repository, I am not sure how to contact you regarding a potential security issue.

Would you kindly provide an email so I can send you the details? Else, simply add a SECURITY.md file with an e-mail to your repository. GitHub recommends this as the best way to ensure security issues are responsibly disclosed.

Look forward to hearing from you, thanks!

**Comment by albogdano** [comment]
Thanks! I've added [SECURITY.md](https://github.com/Erudika/para/blob/master/SECURITY.md) now. Please send the email to support@erudika.com

**Comment by iris-in-sea** [comment]
Hi Ziding,

Would you kindly provided a guide on how to add a SECURITY.md to
improve privacy to my repo. And feel free to reach me via this email.
Many thanks.

Best,
Iris

**Comment by albogdano** [comment]
@iris-in-sea Go to your repo and click the "Security" tab. Then click "Security policy" and "Set up"
