### ISSUE TITLE
para-cli could not read the created object

### ISSUE THREAD

**Issue by songdongsheng** [Erudika/para#8]
C:\opt\para>para-cli ping
✔ Authenticated as: app my-baas (app:my-baas)

C:\opt\para>para-cli create todo.json
✔ Creating todo.json
✔ Created 1 objects with total size of 0 KB.

C:\opt\para>para-cli read --id todo.json
[]

C:\opt\para>type todo.json
{"type":"todo", "name": "buy milk"}
C:\opt\para>

**Comment by albogdano** [comment]
@songdongsheng That's not the correct `id` - todo.json is the name of the file not the `id` of the object. Try `para-cli search "type:todo"`

**Comment by songdongsheng** [comment]
Thanks,  it works:

C:\opt\para>para-cli search "type:todo"
[
  {
    "id": "dG9kby5qc29u",
    "type": "todo",
    "name": "buy milk",
    "stored": true,
    "indexed": false,
    "cached": true,
    "timestamp": 1496311075250,
    "appid": "my-app",
    "votes": 0,
    "objectURI": "/todos/dG9kby5qc29u",
    "plural": "todos"
  }
]
