### ISSUE TITLE
No basic authentication example

### ISSUE THREAD

**Issue by songdongsheng** [Erudika/para#9]
How can I register user with basic authentication ?
Is there an example of register and login with basic authentication ?

How can I use REST API with basic authentication ?
How can I use Java para-client with basic authentication ?

**Comment by albogdano** [comment]
You can register/signin a user with username and password through `paraClient.signIn("password", "user@email.com::pass1234")` (see [Docs](http://paraio.org/docs/#034-api-jwt-signin)). HTTP Basic Authentication is not supported and you can't use the API with it. Each API request must be signed using AWS Signature V4 algorithm (similar to OAuth). 
If want to turn off API signature checking set `para.security.api_security = false`

**Comment by songdongsheng** [comment]
Greate ! 

I can register user with basic authentication now:

curl -i -X POST \
    -H "Content-Type: application/json" \
    -d '{"appid": "app:mybaas", "provider": "password", "token": "me@email.com::pass1234"}' \
    http://localhost:8080/jwt_auth

But when I use command arguments ' -Dadmin_ident=me@email.com' to register admin 'me@email.com', I found the admin user have nothing can do.

This is unreasonable, could you review my pull request https://github.com/Erudika/para/pull/10 ?
